# Этап 1: Сборка приложения
FROM golang:1.19-alpine AS builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы модулей и зависимостей
COPY go.mod .
COPY go.sum .
#COPY go.sum .

# Скачиваем зависимости
RUN go mod download

# Копируем исходный код
COPY . .

# Компилируем приложение
RUN CGO_ENABLED=0 GOOS=linux go build -o api-service .

ENV API_KEY=my-secret-api-key
# Этап 2: Создание финального образа
FROM alpine:latest

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем скомпилированный бинарник из этапа сборки
COPY --from=builder /app/api-service .

# Копируем статические файлы (если есть)
# COPY --from=builder /app/static ./static

# Указываем порт, который будет использовать приложение
EXPOSE 8080

# Команда для запуска приложения
CMD ["./api-service"]